<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAll(): array
    {
        return $this->createQueryBuilder('c')
            ->select('c.category')
            ->orderBy('c.category', 'ASC')
            ->groupBy('c.category')
            ->getQuery()->getResult();
    }
}
