<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getSubscribers(): array
    {
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('newsletter')
            ->orderBy('newsletter.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
