app_controllers:
    resource: '@AppBundle/Controller/Web'
    type: annotation
    options:
        expose: true

rest_controllers:
    resource: '@AppBundle/Controller/Rest'
    type: rest
    prefix: /api
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"