AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        category:
            type: string
            length: 255

    manyToMany:
        articles:
            targetEntity: AppBundle\Entity\Article
            inversedBy: categories
            joinTable:
                name: 'article_category'
                joinColumns:
                    category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    article_id:
                        referencedColumnName: id
